/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.gson.Gson;
import java.io.FileReader;
import java.io.Reader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class App {

    public static void main(String[] args) {
        randomQuote();

    }
public static void randomQuote(){
    Gson gson=new Gson();
    try{
        Reader reader = new FileReader("app/src/main/resources/recentquotes.json");
        Quotes [] convQuotes = gson.fromJson(reader, Quotes[].class);
          int random=(int)Math.floor(Math.random()*(convQuotes.length-0+1)+0);
        System.out.println(convQuotes[random]);
    }catch (Exception ex){
        System.out.println(ex);
    };

}
}
